### ISSUE TITLE
Respecto del README

### ISSUE THREAD

**Issue by delucas** [Promotion-System/jrpg#1]
Vayan pensando el nombre para el juego y agreguen un fragmento en el cual redactarán la pequeña historia que lo ambienta.

**Comment by pablobecerra94** [comment]
Estamos viendo algunos detalles de la historia, en 1 semana o un poco mas la vamos a tener

**Comment by delucas** [comment]
Chicos, este issue sigue abierto, hace tres semanas que está pendiente.
Falta el nombre y la historia. Por favor, priorícenlo.

/cc @pablobecerra94 @CrimsonBraixen @JorgeJOcampo @NahuelKH

**Comment by delucas** [comment]
Falta la historia. Abro otro issue...
