### ISSUE TITLE
Sobre los comentarios

### ISSUE THREAD

**Issue by delucas** [Promotion-System/jrpg#2]
Dado que tenemos un control de versiones, se vuelve innecesario comentar código.
Remuevan el código comentado (por ejemplo, [este](https://github.com/Promotion-System/jrpg/commit/67bb83934a63bdc0d7c801bd5448476d67cf2857#diff-1f6bf1b8dca5e266a08f07456c3d5854R13)) o implementen lo necesario para que funcione.

**Comment by pablobecerra94** [comment]
Ya fue solucionado, no hay codigo comentado
