### ISSUE TITLE
Sobre los números mágicos

### ISSUE THREAD

**Issue by delucas** [Promotion-System/jrpg#3]
Por favor, utilicen constantes para nombrar los números significativos en su sistema.
Por ejemplo, [este](https://github.com/Promotion-System/jrpg/commit/2ab73f76be528cf86d11e93da48cb0f3f5beee23#commitcomment-19527590)

**Comment by delucas** [comment]
Las constantes deberían estar en mayúsculas, @CrimsonBraixen

**Comment by martinartime** [comment]
En el proximo push lo corrijo.
